# Generated by Django 3.0.5 on 2020-04-28 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Epicov',
            fields=[
                ('index', models.IntegerField(primary_key=True, serialize=False)),
                ('strain', models.TextField(blank=True, null=True)),
                ('virus', models.TextField(blank=True, null=True)),
                ('gisaid_epi_isl', models.TextField(blank=True, null=True)),
                ('genbank_accession', models.TextField(blank=True, null=True)),
                ('date', models.TextField(blank=True, null=True)),
                ('region', models.TextField(blank=True, null=True)),
                ('country', models.TextField(blank=True, null=True)),
                ('division', models.TextField(blank=True, null=True)),
                ('location', models.TextField(blank=True, null=True)),
                ('region_exposure', models.TextField(blank=True, null=True)),
                ('country_exposure', models.TextField(blank=True, null=True)),
                ('division_exposure', models.TextField(blank=True, null=True)),
                ('segment', models.TextField(blank=True, null=True)),
                ('length', models.IntegerField(blank=True, null=True)),
                ('host', models.TextField(blank=True, null=True)),
                ('age', models.TextField(blank=True, null=True)),
                ('sex', models.TextField(blank=True, null=True)),
                ('originating_lab', models.TextField(blank=True, null=True)),
                ('submitting_lab', models.TextField(blank=True, null=True)),
                ('authors', models.TextField(blank=True, null=True)),
                ('url', models.TextField(blank=True, null=True)),
                ('title', models.TextField(blank=True, null=True)),
                ('date_submitted', models.TextField(blank=True, null=True)),
                ('id', models.TextField(blank=True, null=True)),
                ('seq', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'epicov',
                'managed': False,
            },
        ),
    ]
